### ISSUE TITLE
Undefined symbols for architecture x86_64: _OBJC_CLASS_$_A0LockReact

### ISSUE THREAD

**Issue by cancan101** [auth0/Lock.ReactNative#8] opened 2015-10-23 20:19 UTC
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_A0LockReact", referenced from:
      objc-class-ref in A0LockReactModule.o
      objc-class-ref in AppDelegate.o
     (maybe you meant: _OBJC_CLASS_$_A0LockReactModule)
```

**Comment by hzalaz** [comment] 2015-10-27 22:12
Any more info? It can be caused by a lot of things so it doesn't help at all to understand the issue

**Comment by cancan101** [comment] 2015-10-28 20:46
This seems to be caused by adding: https://raw.githubusercontent.com/auth0/Lock.ReactNative/master/Pod/Classes/NativeModule/A0LockReactModule.h to the project and then modifying the import to:
```swift
#import <RCTBridgeModule.h>
```

**Comment by hzalaz** [comment] 2015-10-28 20:54
That import should not trigger that issue since the error is from the linker not the compiler. Can you send a sample to support@auth0.com so we can check it out?

**Comment by jsierles** [comment] 2015-10-31 18:50
Same happens here. I've installed the pods, then added all of the Auth0 classes to 'Compiled Sources'.:

```
ndefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_A0AuthParameters", referenced from:
      objc-class-ref in A0LockReact-C1AE470C0E2A5F84.o
  "_OBJC_CLASS_$_A0Lock", referenced from:
      objc-class-ref in A0LockReact-C1AE470C0E2A5F84.o
     (maybe you meant: _OBJC_CLASS_$_A0LockReact)
  "_OBJC_CLASS_$_A0Token", referenced from:
      l_OBJC_$_CATEGORY_A0Token_$_ReactNative in A0Token+ReactNative-9FB45207E18E4E6E.o
  "_OBJC_CLASS_$_A0UserIdentity", referenced from:
      l_OBJC_$_CATEGORY_A0UserIdentity_$_ReactNative in A0UserIdentity+ReactNative-DC40AA839EC6DE77.o
  "_OBJC_CLASS_$_A0UserProfile", referenced from:
      l_OBJC_$_CATEGORY_A0UserProfile_$_ReactNative in A0UserProfile+ReactNative-CD4368D801B6FE79.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by samrose3** [comment] 2015-11-06 03:14
I am also getting this issue..

```

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_A0LockReact", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in LockReactModule.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by hzalaz** [comment] 2015-11-13 18:33
@samrose3 @jsierles we built a different library with should not have this linker issues https://github.com/auth0/react-native-lock-ios so I am closing this issue

**Closed by hzalaz** 2015-11-13 18:33 UTC

**Comment by philcockfield** [comment] 2015-12-28 03:25
Using the latest Podfile as specified in this tutorial https://auth0.com/docs/native-platforms/react-native-ios#ios-react-native-tutorial (which references `react-native-lock-ios`) is giving me this error too.

**Comment by tal952** [comment] 2016-03-15 14:36
+1
